/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ": Lv": ": 等级",
    "! A basic element, it is often quite dangerous but powerful. Fire is key to creating higher temperatures.": "！ 作为基本元素，它通常非常危险但功能强大。 火是产生更高温度的关键。",
    "! Conjuration is the school that studies creating permanent or semi-permanent physical objects out of nothing. An example spell is": "！ 魔法学派研究从无到有创造永久或半永久的物理对象。 一个示例法术是",
    "About": "关于",
    "Air": "气",
    "Allow progress data collection": "允许进度数据收集",
    "Current Goal": "当前目标",
    "Earth": "地",
    "Elements": "元素",
    "Help": "帮助",
    "Actions": "动作",
    "Close": "关闭",
    "Cast Spell": "施法",
    "Events": "事件",
    "Magic Research": "魔法研究",
    "Resources": "资源",
    "Offline Progress": "离线进度",
    "Schools": "学校",
    "Stats": "统计",
    "Welcome back to Magic Research!": "欢迎回到魔法研究！",
    "Time Pieces": "时光碎片",
    "Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!": "时光碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！",
    "Destroy": "销毁",
    "Finished": "已完成",
    "Enchantment": "附魔",
    "Conjuration": "召唤",
    "Campus": "校园",
    "A traveling merchant appeared": "出现了一个旅商",
    "Exp": "经验",
    "Found a staff!": "找到一把法杖！",
    "Gather Mana": "收集法力",
    "Gather more Mana": "收集更多法力",
    "Illusion": "幻觉",
    "Mana": "法力",
    "No spells yet!": "还没有法术！",
    "Ongoing": "进行中",
    "Options": "选项",
    "Pick up": "捡起",
    "Speed up time (10 Time Pieces / sec)": "加速时间（10 时光碎片 / 秒）",
    "\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Buy the pebble": "购买鹅卵石",
    "Decline": "婉拒",
    "Maybe later": "也许以后",
    "Focus your thoughts and gather mana.": "集中你的思想并收集​​法力。",
    ". You think of trying it soon!": ". 你想尽快尝试一下！",
    "By School": "通过学校",
    "Convert Mana into a few pebbles.": "将法力转化为一些鹅卵石。",
    "Convert Mana into some drops of water.": "将法力转化为一些水滴。",
    "Create more Stone and Water": "创造更多的鹅卵石和水",
    "Create Water": "创造水",
    "Create Pebble": "创造鹅卵石",
    "Expand all": "全部展开",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?": "收集法力是有用的，但如果你没有什么用，你为什么要这么做呢？",
    "You are a Wizard": "你是个巫师",
    "You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.": "你已经解锁了施法的能力！ 您可以通过按下屏幕右上角的魔杖图标来施法。",
    "You slowly recall how to cast spells and remember a basic Conjuration spell,": "你回忆起如何施法并慢慢记住一个基本的召唤法术，",
    "Favorites": "偏爱",
    "Stone": "石头",
    "Demo Version": "Demo 版本",
    "Assets from:": "素材来自：",
    "Credits": "鸣谢",
    "Get the full version for Android in": "获取完整版（安卓版）请访问",
    "A game by": "游戏创作者为",
    "the Google Play Store": "Google Play 商店",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "You pick up the staff. It's cursed! You feel your mana getting drained.": "你捡起了法杖。 它被诅咒了！ 你觉得你的法力正在耗尽。",
    "A staff was found on the ground.": "在地上发现了一把法杖。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.\n      \n\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。\n \n\“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?\n\nYou slowly recall how to cast spells and remember a basic Conjuration spell, *Create Pebble*. You think of trying it soon!\n\n**You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.**": "收集法力很有用，但如果你没有什么用，你为什么要这样做呢？\n\n你慢慢回忆起如何施法并记住一个基本的召唤法术，*创建鹅卵石*。 你想尽快尝试一下！\n\n**你已经解锁了施法的能力！ 您可以通过按屏幕右上角的魔杖图标来施法。**",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^(.+)Welcome back to Magic Research!\n      \n\*\*You obtained (.+):timepiece: Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!\*\*$/, '$1欢迎回到魔法研究！\n \n**您获得了 $2:时光碎片：时间碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！**'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);