/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ": Lv": ": 等级",
    "! A basic element, it is often quite dangerous but powerful. Fire is key to creating higher temperatures.": "！ 作为基本元素，它通常非常危险但功能强大。 火是产生更高温度的关键。",
    "! Conjuration is the school that studies creating permanent or semi-permanent physical objects out of nothing. An example spell is": "！ 魔法学派研究从无到有创造永久或半永久的物理对象。 一个示例法术是",
    "About": "关于",
    "Air": "气",
    "Allow progress data collection": "允许进度数据收集",
    "Current Goal": "当前目标",
    "Earth": "地",
    "Elements": "元素",
    "Help": "帮助",
    "Actions": "动作",
    "Close": "关闭",
    "Cast Spell": "施法",
    "Events": "事件",
    "Magic Research": "魔法研究",
    "Resources": "资源",
    "Offline Progress": "离线进度",
    "Schools": "学校",
    "Stats": "统计",
    "Welcome back to Magic Research!": "欢迎回到魔法研究！",
    "Time Pieces": "时光碎片",
    "Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!": "时光碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！",
    "Destroy": "销毁",
    "Finished": "已完成",
    "Enchantment": "附魔",
    "Conjuration": "召唤",
    "Campus": "校园",
    "A traveling merchant appeared": "出现了一个旅商",
    "Exp": "经验",
    "Found a staff!": "找到一把法杖！",
    "Gather Mana": "收集法力",
    "Gather more Mana": "收集更多法力",
    "Illusion": "幻觉",
    "Mana": "法力",
    "No spells yet!": "还没有法术！",
    "Ongoing": "进行中",
    "Options": "选项",
    "Pick up": "捡起",
    "Speed up time (10 Time Pieces / sec)": "加速时间（10 时光碎片 / 秒）",
    "\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Buy the pebble": "购买鹅卵石",
    "Decline": "婉拒",
    "Maybe later": "也许以后",
    "Focus your thoughts and gather mana.": "集中你的思想并收集​​法力。",
    ". You think of trying it soon!": ". 你想尽快尝试一下！",
    "By School": "通过学校",
    "Convert Mana into a few pebbles.": "将法力转化为一些鹅卵石。",
    "Convert Mana into some drops of water.": "将法力转化为一些水滴。",
    "Create more Stone and Water": "创造更多的鹅卵石和水",
    "Create Water": "创造水",
    "Create Pebble": "创造鹅卵石",
    "Expand all": "全部展开",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?": "收集法力是有用的，但如果你没有什么用，你为什么要这么做呢？",
    "You are a Wizard": "你是个巫师",
    "You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.": "你已经解锁了施法的能力！ 您可以通过按下屏幕右上角的魔杖图标来施法。",
    "You slowly recall how to cast spells and remember a basic Conjuration spell,": "你回忆起如何施法并慢慢记住一个基本的召唤法术，",
    "Favorites": "偏爱",
    "Stone": "石头",
    "Demo Version": "Demo 版本",
    "Assets from:": "素材来自：",
    "Credits": "鸣谢",
    "Get the full version for Android in": "获取完整版（安卓版）请访问",
    "A game by": "游戏创作者为",
    "the Google Play Store": "Google Play 商店",
    "Automatically generate Mana and refill your supply.": "自动生成法力并补充你的供应。",
    "/sec": "/秒",
    "Buildings": "建筑",
    "Cost:": "成本：",
    "Water": "水",
    "Build a Mana Shard": "建造一个法力碎片",
    "If only you had a way to store more mana... Then you remember what you had learned as an apprentice, that Mana Shards can increase capacity.": "要是你有办法储存更多的法力就好了……然后你会想起你作为学徒学到的东西，法力碎片可以增加容量。",
    "The mana reserves of the school are building up. Looking at them, you realize they may soon hit their maximum.": "学校的法力储备正在积累，看着他们，你意识到他们可能很快就会达到最大值。",
    "The Mana Shard": "法力碎片",
    "We could buy some if we had enough coins... maybe with some Illusion spell?": "如果我们有足够的金币，我们可以买一些……也许用一些幻觉法术？",
    "You can now build Mana Shards!": "你现在可以建造法力碎片了！",
    "Coins": "金币",
    "Completion Percentage:": "完成百分比：",
    "Global production multiplier:": "全局生产乘数：",
    "Global research multiplier:": "全局研究乘数：",
    "In-game time played (this run):": "游戏内时间（本轮）：",
    "In-game time played (total):": "游戏内时间（总计）：",
    "Increase the amount of mana you can store.": "增加您可以存储的法力值。",
    "Real world time played (this run):": "真实游戏时间（本轮）：",
    "Real world time played (total):": "真实游戏时间（总计）：",
    "Storylines": "故事情节",
    "Total Completed Storylines:": "总完成的故事情节：",
    "Total times retired:": "退休总次数：",
    "Buffs": "增益",
    "The Mana Spouts are Bursting!": "法力喷口正在爆发！",
    "You can now build Warehouses!": "您现在可以建造仓库了！",
    "Warehouse": "仓库",
    "Storage Ideas": "存储理念",
    "Maybe you can use the stone to create more room? It seems like a smart, straightforward idea... you could make a stone warehouse.": "也许你可以用石头创造更多的空间？ 这似乎是一个聪明、直接的想法……你可以建造一个石头仓库。",
    "Accumulating stone is worthwhile. As you watch your reserves getting closer to full, you start thinking if there might be a way to improve the situation.": "积累石头是值得的。 当你看到你的储备越来越接近饱和时，你开始思考是否有办法改善这种情况。",
    "Increases the maximum resources you can store.": "增加您可以存储的最大资源。",
    "Create Rock": "创造石头",
    "Level:": "等级：",
    "Maximum Primary Level in previous runs (MPL):": "本轮游戏中的最高初级等级 (MPL)：",
    "Next level, you will learn:": "下一级，您将学习：",
    "No new spells": "没有新法术",
    "To Next Level:": "到下一级：",
    "Wind Show": "驭风",
    "Options / Save Data": "选项 / 保存数据",
    "Spells": "法术",
    "Introduction": "介绍",
    "Learn how to play the game!": "学习如何玩本游戏！",
    ". This will take you to the magic menu, where you can cast any spell you may have learned.": ". 这将带您进入魔法菜单，您可以在其中施展您可能学到的任何咒语。",
    "- if you are not sure of what to do next, you can follow what it says.": "- 如果您不确定下一步该做什么，您可以按照它说的去做。",
    "In Magic Research, you are the headmaster of a magical institution. Cast spells, accumulate resources, create buildings, and much more to gain prestige and build the best magical school in the world!": "在 魔法研究 中，您是魔法学院的校长。 施展法术、积累资源、建造建筑等等，以获得声望并建立世界上最好的魔法学校！",
    "In the top left corner, you will find": "在左上角，您会发现",
    "In the top right corner, you will find two buttons.": "在右上角，您会发现两个按钮。",
    "takes you to the list of events that have happened recently and allows you to see more information about them or interact with them. In this menu, you can also see": "将您带到最近发生的事件列表，并允许您查看有关它们的更多信息或与它们互动。 在此菜单中，您还可以看到",
    "the magic wand button": "魔杖按钮",
    "the menu button": "菜单按钮",
    "The notification bell button": "通知铃按钮",
    "The other button in the top right corner is": "右上角的另一个按钮是",
    "Welcome to Magic Research!": "欢迎来到魔法研究！",
    "which shows you a breakdown of your current resources and let you access various areas of the game.": "这会向您显示当前资源的细分，并让您访问游戏的各个区域。",
    "your current Goal": "你目前的目标",
    "Time Pieces!": "时光碎片！",
    "Wood!": "木头！",
    "You can now gather": "你现在可以收集",
    "Time to Look Outside": "是时候看看外面了",
    "Our studies of magic are starting to become more fruitful! With our recent advances, we are ready to start broadening our horizons. The campus is big, but there is only so much in it!": "我们对魔法的研究开始变得更有成果了！ 随着我们最近的进展，我们准备开始拓宽我们的视野。 校园很大，但里面只有这么多！",
    "Gather Wood": "收集木头",
    "It seems like there is a nearby forest where we may be able to find wood, which could help us develop our institution even further...": "似乎附近有一片森林，我们可以在那里找到木材，这可以帮助我们进一步发展我们的机构......",
    "Wood": "木头",
    "Collect branches from the nearby forest.": "从附近的森林收集树枝。",
    "Wood Processing": "木材加工",
    "You can now build Lumber Yards!": "你现在可以建造伐木场了！",
    "These trips to the forest are starting to get tedious. You are starting to wonder if there is a way you could make it easier on yourself.": "这些森林之旅开始变得单调乏味。 您开始想知道是否有一种方法可以让您自己更轻松。",
    "Lumber Yard": "伐木场",
    "Perhaps there is a way? Maybe we can reuse the wood we obtained to make something bigger? You get lost in thought as you walk back to campus.": "也许有办法？ 也许我们可以重新利用我们获得的木材来制造更大的东西？ 当你走回校园时，你陷入了沉思。",
    "By the time you arrive, you have figured it out. Lumber yards right at the edge of the forest. It can surely work!": "当你到达时，你已经弄明白了。 伐木场就在森林的边缘。 它一定可以工作！",
    "Processes branches and trees, generating wood automatically.": "加工树枝和树木，自动生成木材。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Mana Spout": "法力喷口",
    "Mana Shard": "法力碎片",
    "(Conjuration Lv": "（召唤法师 等级",
    "(Illusion Lv": "（幻觉 等级",
    "You obtained ": "你获得了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "You pick up the staff. It's cursed! You feel your mana getting drained.": "你捡起了法杖。 它被诅咒了！ 你觉得你的法力正在耗尽。",
    "A staff was found on the ground.": "在地上发现了一把法杖。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.\n      \n\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。\n \n\“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?\n\nYou slowly recall how to cast spells and remember a basic Conjuration spell, *Create Pebble*. You think of trying it soon!\n\n**You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.**": "收集法力很有用，但如果你没有什么用，你为什么要这样做呢？\n\n你慢慢回忆起如何施法并记住一个基本的召唤法术，*创建鹅卵石*。 你想尽快尝试一下！\n\n**你已经解锁了施法的能力！ 您可以通过按屏幕右上角的魔杖图标来施法。**",
    "The mana reserves of the school are building up. Looking at them, you realize they may soon hit their maximum.\n    \nIf only you had a way to store more mana... Then you remember what you had learned as an apprentice, that Mana Shards can increase capacity.\n    \nWe could buy some if we had enough coins... maybe with some Illusion spell?\n\n**You can now build Mana Shards!**": "学校的法力储备正在增加。看着它们，你会意识到它们可能很快就会达到最大值。\n \n要是你有办法储存更多的法力就好了......然后你会想起你作为学徒学到的东西，法力碎片可以增加容量。\n \n如果我们有足够的金币，我们可以买一些......也许用一些幻觉法术？\n\n**你现在可以建造法力碎片了！**",
    "It looks like our mana spouts are suddenly bursting with activity and producing Mana twice as fast!": "看起来我们的法力喷口突然充满活力并以两倍的速度产生法力！",
    " Max": " 上限",
    "Accumulating stone is worthwhile. As you watch your reserves getting closer to full, you start thinking if there might be a way to improve the situation.\n    \nMaybe you can use the stone to create more room? It seems like a smart, straightforward idea... you could make a stone warehouse.\n\n**You can now build Warehouses!**": "积累石头是值得的。 当你看到你的储备越来越接近饱和时，你开始思考是否有办法改善这种情况。\n \n也许你可以用石头创造更多空间？ 这似乎是一个聪明、直接的想法……你可以建造一个石头仓库。\n\n**你现在可以建造仓库了！**",
    "Our studies of magic are starting to become more fruitful! With our recent advances, we are ready to start broadening our horizons. The campus is big, but there is only so much in it!\n    \nIt seems like there is a nearby forest where we may be able to find wood, which could help us develop our institution even further...\n\n**You can now gather:wood: Wood!**": "我们对魔法的研究开始变得更有成果了！ 随着我们最近的进展，我们准备开始拓宽我们的视野。 校园很大，但里面只有这么多！\n\n好像附近有一片森林，我们可以在那里找到木材，这可以帮助我们进一步发展我们的机构......\n\n **你现在可以收集：木头：木头！**",
    "These trips to the forest are starting to get tedious. You are starting to wonder if there is a way you could make it easier on yourself.\n    \nPerhaps there is a way? Maybe we can reuse the wood we obtained to make something bigger? You get lost in thought as you walk back to campus.\n\nBy the time you arrive, you have figured it out. Lumber yards right at the edge of the forest. It can surely work!\n\n**You can now build Lumber Yards!**": "这些森林之旅开始变得单调乏味。 您开始想知道是否有一种方法可以让您自己更轻松。\n \n也许有一种方法？ 也许我们可以重新利用我们获得的木材来制造更大的东西？ 当您走回校园时，您陷入了沉思。\n\n当您到达时，您已经想通了。 伐木场就在森林的边缘。 它肯定可以工作！\n\n**你现在可以建造伐木场了！**",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^(.+)Welcome back to Magic Research!\n      \n\*\*You obtained (.+):timepiece: Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!\*\*$/, '$1欢迎回到魔法研究！\n \n**您获得了 $2:时光碎片：时间碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！**'],
    [/^(.+)Welcome back to Magic Research!\n      \n\*\*You obtained (.+):timepiece: Time Pieces!\*\*$/, '$1欢迎回到魔法研究！\n \n**您获得了 $2:时光碎片：时间碎片！ **'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Conjuration Lv(.+) \(Primary\)$/, '召唤 等级$1（初级）'],
    [/^Illusion Lv(.+)$/, '幻觉 等级$1'],
    [/^Enchantment Lv(.+)$/, '附魔 等级$1'],
    [/^s bursting with activity! \((.+) sec\)$/, '充满活力！（$1 秒）'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) days, ([\d\.]+):([\d\.]+):([\d\.]+)$/, '$1 天，$2:$3:$4'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);