/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ": Lv": ": 等级",
    "! A basic element, it is often quite dangerous but powerful. Fire is key to creating higher temperatures.": "！ 作为基本元素，它通常非常危险但功能强大。 火是产生更高温度的关键。",
    "! Conjuration is the school that studies creating permanent or semi-permanent physical objects out of nothing. An example spell is": "！ 魔法学派研究从无到有创造永久或半永久的物理对象。 一个示例法术是",
    "About": "关于",
    "Air": "气",
    "Allow progress data collection": "允许进度数据收集",
    "Current Goal": "当前目标",
    "Earth": "地",
    "Elements": "元素",
    "Help": "帮助",
    "Actions": "动作",
    "Close": "关闭",
    "Cast Spell": "施法",
    "Events": "事件",
    "Magic Research": "魔法研究",
    "Resources": "资源",
    "Offline Progress": "离线进度",
    "Schools": "学校",
    "Stats": "统计",
    "Welcome back to Magic Research!": "欢迎回到魔法研究！",
    "Time Pieces": "时光碎片",
    "Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!": "时光碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！",
    "Destroy": "销毁",
    "Finished": "已完成",
    "Enchantment": "附魔",
    "Conjuration": "召唤",
    "Campus": "校园",
    "A traveling merchant appeared": "出现了一个旅商",
    "Exp": "经验",
    "Found a staff!": "找到一把法杖！",
    "Gather Mana": "收集法力",
    "Gather more Mana": "收集更多法力",
    "Illusion": "幻觉",
    "Mana": "法力",
    "No spells yet!": "还没有法术！",
    "Ongoing": "进行中",
    "Options": "选项",
    "Pick up": "捡起",
    "Speed up time (10 Time Pieces / sec)": "加速时间（10 时光碎片 / 秒）",
    "\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Buy the pebble": "购买鹅卵石",
    "Decline": "婉拒",
    "Maybe later": "也许以后",
    "Focus your thoughts and gather mana.": "集中你的思想并收集​​法力。",
    ". You think of trying it soon!": ". 你想尽快尝试一下！",
    "By School": "学校分类",
    "Convert Mana into a few pebbles.": "将法力转化为一些鹅卵石。",
    "Convert Mana into some drops of water.": "将法力转化为一些水滴。",
    "Create more Stone and Water": "创造更多的鹅卵石和水",
    "Create Water": "创造水",
    "Create Pebble": "创造鹅卵石",
    "Expand all": "全部展开",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?": "收集法力是有用的，但如果你没有什么用，你为什么要这么做呢？",
    "You are a Wizard": "你是个巫师",
    "You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.": "你已经解锁了施法的能力！ 您可以通过按下屏幕右上角的魔杖图标来施法。",
    "You slowly recall how to cast spells and remember a basic Conjuration spell,": "你回忆起如何施法并慢慢记住一个基本的召唤法术，",
    "Favorites": "偏爱",
    "Stone": "石头",
    "Demo Version": "Demo 版本",
    "Assets from:": "素材来自：",
    "Credits": "鸣谢",
    "Get the full version for Android in": "获取完整版（安卓版）请访问",
    "A game by": "游戏创作者为",
    "the Google Play Store": "Google Play 商店",
    "Automatically generate Mana and refill your supply.": "自动生成法力并补充你的供应。",
    "/sec": "/秒",
    "Buildings": "建筑",
    "Cost:": "成本：",
    "Water": "水",
    "Build a Mana Shard": "建造一个法力碎片",
    "If only you had a way to store more mana... Then you remember what you had learned as an apprentice, that Mana Shards can increase capacity.": "要是你有办法储存更多的法力就好了……然后你会想起你作为学徒学到的东西，法力碎片可以增加容量。",
    "The mana reserves of the school are building up. Looking at them, you realize they may soon hit their maximum.": "学校的法力储备正在积累，看着他们，你意识到他们可能很快就会达到最大值。",
    "The Mana Shard": "法力碎片",
    "We could buy some if we had enough coins... maybe with some Illusion spell?": "如果我们有足够的金币，我们可以买一些……也许用一些幻觉法术？",
    "You can now build Mana Shards!": "你现在可以建造法力碎片了！",
    "Coins": "金币",
    "Completion Percentage:": "完成百分比：",
    "Global production multiplier:": "全局生产乘数：",
    "Global research multiplier:": "全局研究乘数：",
    "In-game time played (this run):": "游戏内时间（本轮）：",
    "In-game time played (total):": "游戏内时间（总计）：",
    "Increase the amount of mana you can store.": "增加您可以存储的法力值。",
    "Real world time played (this run):": "真实游戏时间（本轮）：",
    "Real world time played (total):": "真实游戏时间（总计）：",
    "Storylines": "故事情节",
    "Total Completed Storylines:": "总完成的故事情节：",
    "Total times retired:": "退休总次数：",
    "Buffs": "增益",
    "The Mana Spouts are Bursting!": "法力喷泉正在爆发！",
    "You can now build Warehouses!": "您现在可以建造仓库了！",
    "Storage Ideas": "存储理念",
    "Maybe you can use the stone to create more room? It seems like a smart, straightforward idea... you could make a stone warehouse.": "也许你可以用石头创造更多的空间？ 这似乎是一个聪明、直接的想法……你可以建造一个石头仓库。",
    "Accumulating stone is worthwhile. As you watch your reserves getting closer to full, you start thinking if there might be a way to improve the situation.": "积累石头是值得的。 当你看到你的储备越来越接近饱和时，你开始思考是否有办法改善这种情况。",
    "Increases the maximum resources you can store.": "增加您可以存储的最大资源。",
    "Create Rock": "创造石头",
    "Level:": "等级：",
    "Maximum Primary Level in previous runs (MPL):": "本轮游戏中的最高初级等级 (MPL)：",
    "Next level, you will learn:": "下一级，您将学习：",
    "No new spells": "没有新法术",
    "To Next Level:": "到下一级：",
    "Wind Show": "驭风表演",
    "Options / Save Data": "选项 / 保存数据",
    "Spells": "法术",
    "Introduction": "介绍",
    "Learn how to play the game!": "学习如何玩本游戏！",
    ". This will take you to the magic menu, where you can cast any spell you may have learned.": ". 这将带您进入魔法菜单，您可以在其中施展您可能学到的任何咒语。",
    "- if you are not sure of what to do next, you can follow what it says.": "- 如果您不确定下一步该做什么，您可以按照它说的去做。",
    "In Magic Research, you are the headmaster of a magical institution. Cast spells, accumulate resources, create buildings, and much more to gain prestige and build the best magical school in the world!": "在 魔法研究 中，您是魔法学院的校长。 施展法术、积累资源、建造建筑等等，以获得声望并建立世界上最好的魔法学校！",
    "In the top left corner, you will find": "在左上角，您会发现",
    "In the top right corner, you will find two buttons.": "在右上角，您会发现两个按钮。",
    "takes you to the list of events that have happened recently and allows you to see more information about them or interact with them. In this menu, you can also see": "将您带到最近发生的事件列表，并允许您查看有关它们的更多信息或与它们互动。 在此菜单中，您还可以看到",
    "the magic wand button": "魔杖按钮",
    "the menu button": "菜单按钮",
    "The notification bell button": "通知铃按钮",
    "The other button in the top right corner is": "右上角的另一个按钮是",
    "Welcome to Magic Research!": "欢迎来到魔法研究！",
    "which shows you a breakdown of your current resources and let you access various areas of the game.": "这会向您显示当前资源的细分，并让您访问游戏的各个区域。",
    "your current Goal": "你目前的目标",
    "Time Pieces!": "时光碎片！",
    "Wood!": "木头！",
    "You can now gather": "你现在可以收集",
    "Time to Look Outside": "是时候看看外面了",
    "Our studies of magic are starting to become more fruitful! With our recent advances, we are ready to start broadening our horizons. The campus is big, but there is only so much in it!": "我们对魔法的研究开始变得更有成果了！ 随着我们最近的进展，我们准备开始拓宽我们的视野。 校园很大，但里面只有这么多！",
    "Gather Wood": "收集木头",
    "It seems like there is a nearby forest where we may be able to find wood, which could help us develop our institution even further...": "似乎附近有一片森林，我们可以在那里找到木材，这可以帮助我们进一步发展我们的机构......",
    "Wood": "木头",
    "Collect branches from the nearby forest.": "从附近的森林收集树枝。",
    "Wood Processing": "木材加工",
    "You can now build Lumber Yards!": "你现在可以建造伐木场了！",
    "These trips to the forest are starting to get tedious. You are starting to wonder if there is a way you could make it easier on yourself.": "这些森林之旅开始变得单调乏味。 您开始想知道是否有一种方法可以让您自己更轻松。",
    "Perhaps there is a way? Maybe we can reuse the wood we obtained to make something bigger? You get lost in thought as you walk back to campus.": "也许有办法？ 也许我们可以重新利用我们获得的木材来制造更大的东西？ 当你走回校园时，你陷入了沉思。",
    "By the time you arrive, you have figured it out. Lumber yards right at the edge of the forest. It can surely work!": "当你到达时，你已经弄明白了。 伐木场就在森林的边缘。 它一定可以工作！",
    "Processes branches and trees, generating wood automatically.": "加工树枝和树木，自动生成木材。",
    "Water Storage": "储水",
    "You can now build Water Tanks!": "你现在可以建造水箱了！",
    "You feel a surge of inspiration, as you realize you could build a container. Then you figure it's downright obvious.": "当您意识到自己可以构建一个容器时，您会感到灵感涌动。 然后你认为这是非常明显的。",
    "You have been struggling with water storage for a while. Creating it is easy, but you have nowhere to place it - it just drops to the ground!": "您已经为储水问题苦苦挣扎了一段时间。 创建它很容易，但您无处放置它 - 它会掉到地上！",
    "You set out to build a water tank with stone and wood.": "你着手用石头和木头建造一个水箱。",
    "Allows you to stockpile water.": "允许你储存水。",
    "Create a basic entertainment show based on petty illusions.": "根据琐碎的幻想创建一个基本的娱乐节目。",
    "Enchant Mana Spouts": "附魔法力喷泉",
    "Magic Show": "魔术表演",
    "Magically alter your Mana Spouts to produce more mana for a limited time.": "神奇地改变你的 法力喷泉 以在有限的时间内产生更多的法力。",
    "produced by Mana Spouts for 30 sec.": "由 法力喷泉 产生，持续 30 秒。",
    "\"Wow, this would be great source material,\" she says.": "“哇，这将是很好的原始材料，”她说。",
    "A wild researcher appeared": "一位狂野的研究员出现了",
    "An enthusiastic lady looks at your Mana and notices the large amount you have.": "一位热情的女士看到您的法力值，并注意到您拥有大量的法力值。",
    "Continue": "继续",
    "Hire the Researcher": "雇用研究员",
    "Congratulations!": "恭喜！",
    "Conjuration Level Up!": "召唤等级提升！",
    "Create a larger rock to get plenty of Stone.": "创造一个更大的岩石来获得大量的石头。",
    "New spells learned:": "学到的新法术：",
    "Your Conjuration level is now 2!": "",
    "A Pile of Stone": "一堆石头",
    "A Pile of Wood": "一堆木头",
    "You find a pile of stone as you walk through campus. You are not sure why it's there, but it seems misplaced. You decide to take it.": "当你穿过校园时，你会发现一堆石头。 你不确定它为什么在那里，但它似乎放错了地方。 你决定接受它。",
    "You stumble upon a pile of wood as you walk through campus. You are not sure why it's there, but it seems misplaced. You decide to take it.": "当你穿过校园时，你偶然发现了一堆木头。 你不确定它为什么在那里，但它似乎放错了地方。 你决定接受它。",
    "You look at her, perplexed and somewhat confused. Then she continues explaining.": "你看着她，既困惑又有些迷茫。 然后她继续解释。",
    "\"Large amounts of Mana are hard to come by, and are almost a requirement for the successful study of Magic.\"": "“大量的法力来之不易，几乎是魔法学习成功的必要条件。”",
    "\"Are you trying to study magic here? This is exciting!": "\"你是想在这里学习魔法吗？这太刺激了！",
    "\"But there's a problem. There's nowhere for them to stay in. I have an idea for a cabin, but... we'll need to build it, first. Oh well.. back to work,\" she mentions, as she turns away and continues focusing on her research.": "\“但是有一个问题。他们没有地方可以住。我有一个小木屋的想法，但是......我们首先需要建造它。哦，好吧......回去工作，“她提到，当她转身继续专注于她的研究时。",
    "\"Perfect! I will get started right away. I'm sure this is the beginning of a very fruitful relationship for us both!,\" she exclaims.": "“完美！我会马上开始。我相信这对我们双方来说是一段非常富有成果的关系的开始！”她惊呼道。",
    "\"So what will it be?\"": "\"那会是什么呢？\"",
    "Housing for Researchers": "研究人员住房",
    "Continue doing research": "继续进行研究",
    "I'd be willing to work here for a small price... let's say 200 Coins. Of course, you would be the first to learn what I find out, and you would be able to tell me what I should focus on,\" she says earnestly.": "我愿意以很少的价格在这里工作……比方说 200 金币。 当然，你会是第一个知道我发现了什么，你会告诉我我应该关注什么，”她认真地说。",
    "Pay 200 Coins": "付 200 金币",
    "Research": "研究",
    "You can now build Researcher Cabins!": "你现在可以建造研究员小屋了！",
    "You have unlocked the \"Research\" feature! You may find it on the left-side menu.": "您已解锁“研究”功能！ 您可以在左侧菜单中找到它。",
    "You ponder her words for some time. Regardless of her feelings, you recognize that double the researchers could greatly speed things up. You think of possibly building a Researcher Cabin as she suggested, and hiring an extra researcher.": "你思考了她的话一段时间。 不顾她的感受，你意识到双倍的研究人员可以大大加快速度，你考虑可能按照她的建议建造一个研究人员小屋，并雇用一个额外的研究人员。",
    "You produce 200 coins out of your pockets, and hand them over to the researcher. She looks at the coins and puts them away in the pockets of her robes.": "你从口袋里掏出 200 个金币，交给研究人员。 她看了看硬币，把它们放在长袍的口袋里。",
    "Your researcher comes up to you. \"Studying here has been great so far!\", she says. \"But it certainly is somewhat lonely... it would be great to have company. We could get double the work done; imagine how fast we could discover new things!\", she exclaims.": "你的研究员来找你。 “到目前为止，在这里学习一直很棒！”，她说。 “但它确实有点孤独……有人陪伴会很棒。我们可以完成双倍的工作；想象一下我们发现新事物的速度有多快！”，她感叹道。",
    "Housing for researchers to live in campus.": "供研究人员住在校园内的住房。",
    "Your Researchers are Inspired!": "您的研究人员受到启发！",
    "You wonder if there might be a way to somehow automate this, as it's starting to feel a bit dull. But thinking about it, you can't figure out any solution...": "你想知道是否有办法以某种方式自动执行此操作，因为它开始感觉有点乏味。 但是想想也想不出什么办法……",
    "Use Time Pieces": "使用时光碎片",
    "Use all your time pieces to get a large amount of research.": "使用你所有的 时光碎片 来获得大量的研究。",
    "Researchers available:": "可用的研究人员：",
    "Researcher capacity:": "研究员容量：",
    "Instantly obtain 3 min of research": "立即获得 3 分钟的研究",
    "How many times have you manually cast a spell by now? You have lost count. It certainly is not difficult for you. However, there is real repetition to these casts.": "你现在手动施法多少次了？ 你数不清了。 这对你来说当然不难。 但是，这些演员表确实存在重复。",
    "Hire Researcher": "雇用研究员",
    "Hire a new researcher to gain magical experience faster.": "雇用一名新研究员以更快地获得魔法经验。",
    "Exp per researcher:": "每个研究员的经验值：",
    "Casting Spells is Repetitive": "施法是重复的",
    "/ sec": "/ 秒",
    "(Primary)": "(初级)",
    "Apprentices Need Sleep": "学徒需要睡眠",
    "Create Water II": "创造水 II",
    "Convert Mana into a larger chunk of water.": "将法力转化为更大的水滴。",
    "Finish the \"Apprentices Need Sleep\" event": "完成“学徒需要睡觉”事件",
    "\"I have a great idea!\", she says. \"This is my cousin. He is a wizard-in-training... an apprentice wizard,\" she continues, while gazing at him, before looking at you once more.": "“我有个好主意！”她说。 “这是我的堂兄。他是一名受训巫师……一名学徒巫师，”她继续说道，同时注视着他，然后又再次看着你。",
    "\"It is a honor to meet you, headmaster,\" exclaims the apprentice, while bowing at you somewhat too deeply.": "“很荣幸见到您，校长，”学徒大声说道，同时向您深深地鞠了一躬。",
    "\"There's just a little problem,\" the researcher continues. \"There is nowhere for him to sleep in! We'll need to build something.\"": "“只是有点问题，”研究人员继续说道。 “他没有地方睡觉！我们需要建造一些东西。”",
    "Build an Apprentice Dorm": "建造一个学徒宿舍",
    "Housing for apprentices, which can help cast spells.": "学徒的住房，可以帮助施法。",
    "manually. You reassure the researcher and her cousin that you will think about it, and you walk away, starting to picture what you would need to construct suitable housing for your first apprentice.": "手动。 你向研究人员和她的堂兄保证你会考虑这件事，然后你走开了，开始想象你需要什么来为你的第一个学徒建造合适的住房。",
    "The researcher continues. \"It'd be great to have him stay here! He could help you cast spells and continue improving our campus. Besides, a magical institution makes no sense without people who'd like to learn. What do you think?\", she asks you.": "研究人员继续说道。 \"让他留在这里就好了！他可以帮助你施法，继续改善我们的校园。而且，没有愿意学习的人，一个魔法机构就没有意义。你怎么看？\",她问你。",
    "You can now build Apprentice Dorms!": "你现在可以建造学徒宿舍了！",
    "You recall thinking about how tedious it was to cast spells. This could be a big help!": "你记得想过施法是多么乏味。 这可能是一个很大的帮助！",
    "You saw it coming. Still, you can't wait - you've had enough casting": "你看到它来了。 不过，你等不及了——你已经受够了",
    "Your researcher walks up to you. She is together with a shaky individual, who seems to be barely breaking into adulthood and appears scared at your sight.": "你的研究员走到你身边。 她和一个似乎刚刚进入成年期并且看起来很害怕的人在一起。",
    "A metal-reinforced building that produces mana.": "一座产生法力的金属加固建筑。",
    "As you slowly start getting more and more iron, you think of a plan to improve on your Mana Spouts. You are thinking that, by adding iron, you should be able to create a structure that can produce mana at a much faster rate than a simple spout.": "随着您慢慢开始获得越来越多的铁，您想到了一个改进 法力喷泉 的计划。 您在想，通过添加铁，您应该能够创建一种结构，其产生法力的速度比简单的喷口快得多。",
    "Create Iron Ore": "创造铁矿石",
    "Gather Iron": "收集铁",
    "Iron": "铁",
    "Materialize a piece of iron ore.": "实体化一块铁矿石。",
    "Mine for iron.": "铁矿。",
    "The Quarry": "采石场",
    "You can now build Mana Geysers!": "你现在可以建造法力间歇泉了！",
    "You will definitely require a lot of iron, but it'll be worth it in the long run, you tell yourself. Mana is the cornerstone of magic!": "你肯定需要很多铁，但从长远来看，这是值得的，你告诉自己。 法力是魔法的基石！",
    "Illusion Level Up!": "幻觉升级了！",
    "Create an entertainment show based on wind gusts.": "创建一个基于阵风的娱乐节目。",
    "Coin Storage": "金币存储",
    "Allows you to store more coins safely.": "让您安全地存储更多金币。",
    "s have been useful; stone has proven to be a good material for tons of things. You think about using it for a specialized building for money storage. You are concerned about bandits, but are convinced it'll be worth it in the long run.": "很有用； 事实证明，石头是制作大量物品的好材料。 您考虑将其用于专门用于存放货币的建筑物。 你担心土匪，但相信从长远来看这是值得的。",
    "You are managing to stockpile large amounts of coins! It would be wise to find a place to put them in.": "您正在设法储存大量金币！ 找个地方把它们放进去是明智的。",
    "ou can now build Vaults!": "你现在可以建造金库了！",
    "Copy savefile to clipboard": "将存档复制到剪贴板",
    "Data collection": "数据采集",
    "Import savefile": "导入存档",
    "Load File": "加载文件",
    "Performance": "性能",
    "Save File": "保存存档",
    "Target FPS:": "目标帧率：",
    "The game collects and sends small amounts of data related to your progress through the game in order to improve the game. If you prefer, you may opt out of this data collection.": "游戏会收集并发送与您的游戏进度相关的少量数据，以改进游戏。 如果您愿意，您可以选择退出此数据收集。",
    "WARNING: This will erase your current save! Make sure you have backed up your data!": "警告：这将删除您当前的保存！ 确保您已备份数据！",
    "You may import save data by pasting it here.": "您可以通过在此处粘贴来导入保存数据。",
    "You may persist your save data by copying it to the clipboard and storing it anywhere you'd like.": "您可以通过将保存的数据复制到剪贴板并将其存储在您想要的任何位置来保留保存的数据。",
    "You may set your target FPS here. Higher FPS will make the game smoother but it could affect battery power and CPU usage.": "您可以在此处设置目标 FPS。 更高的 FPS 将使游戏更流畅，但它可能会影响电池电量和 CPU 使用率。",
    "Create Boulder": "创造巨石",
    "Create a giant rock and boost your Stone reserves.": "创造一块巨大的岩石并增加你的石头储备。",
    "\"Gathering resources like wood and iron is great\", she continues. \"Wouldn't it even be more interesting if we could make more complex stuff from them?\"": "“收集木材和铁等资源很棒”，她继续说道。 \“如果我们能用它们制造更复杂的东西，会不会更有趣？”",
    "\"Headmaster, I think you may already be aware, but - now that we have a proper, true magical institution, we should start thinking about the": "\“校长，我想你可能已经意识到了，但是——既然我们有了一个合适的、真正的魔法机构，我们应该开始考虑",
    "\"If we had a crafting station, we could make a lot of these... if only it wasn't so expensive to build, I could do it myself and learn more about it!\", she says, somewhat frustrated.": "“如果我们有一个制作站，我们就可以制作很多这样的东西……只要建造起来不那么昂贵，我就可以自己动手做并了解更多！”她说，有些沮丧。",
    "\"Is that... housing I could use?\", he says, with a timid voice. You nod, and ask him if he'd like to become your first apprentice. He shakes, visibly and clearly nervous.": "“那是……我可以使用的住房吗？”他用胆怯的声音说道。 你点点头，问他愿不愿意做你的第一个学徒。 他颤抖着，显然很紧张。",
    "\"It could really take our school to new heights!\", she exclaims.": "“它真的可以让我们的学校更上一层楼！”她感叹道。",
    "\"No, that's not what I meant\", she says, unhappily. \"Buildings are huge! I'm thinking more of useful, smaller things. Potions? Weapons? Magical items?\"": "“不，我不是那个意思”，她不高兴地说。 \“建筑物很大！我在想更有用的、更小的东西。药水？武器？魔法物品？”",
    "\"That would be great... I-It's a honor, to be able to learn from one such as you, headmaster. I'll move in right away.\"": "“那太好了……我、校长，我很荣幸能向您这样的人学习。我马上就搬进来。”",
    "Any bonuses you obtained from \"(Storyline)\" events will remain;": "您从“（故事情节）”活动中获得的任何奖金都将保留；",
    "Any unlocked schools or elements will stay unlocked;": "任何解锁的学校或元素将保持解锁状态；",
    "Apprentices": "学徒",
    "Apprentices Available:": "学徒可用：",
    "Apprentices will cast the spell they are assigned to every": "学徒将施展分配给他们的法术",
    "Build a Crafting Station (2000 Coins, 2000 Wood, 100 Iron)": "建造一个工艺站（2000 金币、2000 木材、100 铁）",
    "Build the crafting station": "建造手工站",
    "Construction for the first apprentice dorm is finished! You celebrate to a small audience. You notice the apprentice from before is still there. You approach him, though he still seems fearful and bows deeply.": "第一个学徒宿舍建设完成！ 你向一小群观众庆祝。 你注意到之前的学徒还在。 你走近他，尽管他看起来仍然很害怕并且深深地鞠躬。",
    "Crafting Station": "制作站",
    "Create Iron Bar": "制造铁锭",
    "Create Water III": "创造水 III",
    "Do you want to retire?": "你想退休吗？",
    "Everything will revert back to its initial state, except:": "一切都会恢复到初始状态，除了：",
    "If you retire,": "如果你退休",
    "Load": "加载",
    "Loadouts:": "装载：",
    "Old Book of Conjuration": "古老的召唤书",
    "One of your researchers seems to have come across a dusty book. The book seems to contain knowledge about Conjuration. Thrilled, your researchers get back to work with the new knowledge.": "您的一位研究人员似乎遇到了一本布满灰尘的书。 这本书似乎包含有关召唤的知识。 激动的是，您的研究人员重新开始使用新知识开展工作。",
    "Pause Apprentices": "暂停学徒",
    "Requires:": "必需的：",
    "Retire": "退休",
    "Retirement": "退休",
    "sec, if they can. More apprentices will cause the spell to be cast more often.": "秒，如果可以的话。 更多的学徒会导致更频繁地施放法术。",
    "The First Apprentice": "第一个学徒",
    "The Tournament of Magic": "魔法大赛",
    "Tournament of Magic": "魔法大赛",
    "When you retire, you will be able to choose a new primary school and element.": "退休后，您将可以选择新的小学和元素。",
    "You aren't sure whether to pay heed to it - why would you need things like weapons in a magical institution? You think about it some more...": "你不确定是否要注意它 - 为什么你需要在魔法机构中使用武器之类的东西？ 你再考虑一下...",
    "You continue listening to her.": "你继续听她说。",
    "You gain 2231 Conjuration experience!": "你获得 2231 点召唤经验！",
    "You have built up enough knowledge that you feel it might be enough. You consider retirement.": "你已经积累了足够的知识，你觉得这可能就足够了。 你考虑退休。",
    "You have unlocked Apprentices! Apprentices can automatically cast spells for you after a set amount of time. You may manage them in the Apprentices section, in the left-hand-side menu.": "您已解锁学徒！ 学徒可以在一定时间后自动为您施法。 您可以在左侧菜单的“学徒”部分管理它们。",
    "You talk to her some more, and you start feeling like it is a great goal to have... though you know you are nowhere close to reaching it. At least for now...": "你又和她谈了一会儿，你开始觉得这是一个伟大的目标……虽然你知道你离实现它还差得很远。 至少现在（是...",
    "You try to convey to your researcher that we have, in fact, been creating complex things from resources: the buildings. But she frowns.": "您试图向您的研究人员表明，我们实际上一直在从资源（建筑物）中创造复杂的事物。 但她皱着眉头。",
    "You will gain a boost to research, building production and loot based on the maximum level you have ever attained on your primary school (MPL), as well as on the sum of the MPLs you have attained on each school you have unlocked.": "根据您在小学 (MPL) 达到的最高水平，以及您在已解锁的每所学校达到的 MPL 总和，您将获得研究、建筑生产和战利品的提升。",
    "you will reset the game.": "您将重置游戏。",
    "Your focus is interrupted by your researcher, who yells at you. \"Headmaster!\", she says.": "你的注意力被你的研究员打断了，他对你大喊大叫。 “校长！”她说。",
    "Your researcher approaches you and mentions something to you.": "您的研究人员接近您并向您提及一些事情。",
    ".\" You are not sure of what she means by that, but she continues: \"The Tournament of Magic is a competition between magical institutions. It is a major event in regards to the research of magic, and those who manage to compete in it - let alone the winner - are sure to get great fame and prosperity.\"": ".\" 你不确定她的意思，但她继续说道：\"魔法锦标赛是魔法机构之间的比赛。 这是魔法研究界的一件大事，能够参赛的人，别说胜出者，必定会名利双收。”",
    "Bubble Show": "泡沫表演",
    "Convert Mana into a large amount of water.": "将法力转化为大量的水。",
    "Materialize an iron bar.": "实体化一根铁锭。",
    "Create a fun entertainment show based on bubbles.": "创造一个基于泡泡的有趣娱乐节目。",
    "Unpause Apprentices": "取消暂停学徒",
    "Before you begin, you will need to choose a primary school of magic and a primary element. While you may cast spells from any schools, it will be easier to learn new spells in your primary school. Your primary element selection may affect availability and effects of various spells, among other things. You will be able to change these (via retirement) later in the game.": "在开始之前，您需要选择一个小学魔法学校和一个初级元素。 虽然你可以从任何学校施展法术，但在你的小学学习新法术会更容易。 您选择的主要元素可能会影响各种法术的可用性和效果等。 您将能够在游戏后期更改这些（通过退休）。",
    "Fire": "火",
    "Data Collection Notice": "数据收集通知",
    "If it's your first time playing, choosing Conjuration is recommended.": "如果您是第一次玩，建议选择召唤。",
    "In Magic Research, you are the headmaster of a magical institution. What sort of adventures await you?": "在 魔法研究 中，您是魔法学院的校长。 什么样的冒险等待着你？",
    "Magic Research optionally collects and sends a small amount of data related to your progress throughout the game in order to improve the game. If you'd like to help improve the game, you can opt into this data collection. You may change this setting anytime in the \"Options\" menu.": "魔法研究 有选择地收集和发送与您在整个游戏过程中的进度相关的少量数据，以改进游戏。 如果您想帮助改进游戏，您可以选择加入此数据收集。 您可以随时在“选项”菜单中更改此设置。",
    "Please choose a primary element.": "请选择一个基础元素。",
    "Please choose a primary school of magic.": "请选择一所基础魔法学校。",
    "Start the Game!": "开始游戏！",
    "Welcome to Magic Research": "欢迎来到魔法研究",
    "good deal. I can't go lower than 150 coins, though. Are you interested?": "很划算。 不过，我不能低于 150 个硬币。 你感兴趣吗？",
    "very": "非常",
    "You use your Illusion prowess to charm the merchant into thinking positively about you. Without noticing, he says: \"Actually... 1500 coins is quite a high price. I'd be happy to give you a": "你用你的幻觉能力来吸引商人对你产生积极的看法。 他下意识地道：“其实……1500币的价格不高，我很乐意给你一个",
    "\"Great doing business with you!\", he exclaims, taking your coins. Placing the pebble back inside the bag, he hands over the bag to you.": "“和你做生意真好！”他接过你的硬币时大声说道。 把鹅卵石放回袋子里，他把袋子递给你。",
    "This magical stone will come in handy!": "这块神奇的石头会派上用场的！",
    "Enchant Lumber Yards": "附魔伐木场",
    "Enchantment Level Up!": "附魔等级提升！",
    "Create an impressive entertainment show based on fire.": "用火创造令人印象深刻的娱乐节目。",
    "Magically alter your Lumber Yards to work faster for a limited time.": "神奇地改变你的伐木场，在有限的时间内更快地工作。",
    "Flame Show": "火焰表演",
    "produced by Lumber Yards for 30 sec.": "由伐木场生产，持续 30 秒。",
    "A basic cloak made out of cloth.": "用布料制成的基本斗篷。",
    "A crafting station... You wonder if you might be able to do something with it right away?": "一个制作站……你想知道你是否可以马上用它做点什么？",
    "A Really Hot Oven": "一个非常热的烤箱",
    "Accessory": "配饰",
    "All": "阿莱斯",
    "Basic shoes made out of cloth. Makes walking somewhat easier.": "布料制成的基本款鞋子。 让走路更轻松一些。",
    "Body": "身体",
    "Cloak": "披风",
    "Cloth": "衣服",
    "Cloth Shoes": "布鞋",
    "Craft": "制作",
    "Craft an item": "制作一个物品",
    "Craft Items": "制作物品",
    "Crafting": "制作",
    "Equipment": "装备",
    "Furnace": "熔炉",
    "Hand": "手",
    "Inventory": "库存",
    ": Empty": "：空",
    "\"Conjuration and Enchantment,\" says your researcher, as she passes by you with the apprentice. \"Focus our research in those schools, and we should be able to make items.\" They head outside together.": "“咒法和附魔，”你的研究员说，她带着学徒从你身边经过。 “把我们的研究重点放在那些学校，我们应该可以制造物品。” 他们一起向外走去。",
    "\"I-I have been thinking about crafting, but it's very hard to shape metal right now,\" he says. \"Maybe if we had a really hot flame, we would be able to be much more effective with crafting... maybe even make real weapons?\"": "“我-我一直在考虑手工制作，但现在很难塑造金属，”他说。 \“也许如果我们有真正炽热的火焰，我们就能更有效地制作……甚至可以制作真正的武器？\”",
    "It was difficult, but the crafting station is finished! Your researcher, filled with joy, runs towards it and examines it from every angle. You notice your apprentice also taking notice of it, and looking at it curiously.": "这很困难，但制作站已经完成了！ 您的研究人员满怀喜悦地奔向它，并从各个角度审视它。 你注意到你的徒弟也注意到了它，并且好奇地看着它。",
    "Material": "材料",
    "Total owned: 0": "拥有总数：0",
    "Unequip": "卸下装备",
    "You can now build Furnaces!": "你现在可以建造熔炉了！",
    "You have unlocked the \"Inventory\" and \"Crafting\" features! You can access your inventory via the left-side menu. You can craft from the inventory screen.": "您已经解锁了“库存”和“制作”功能！ 您可以通过左侧菜单访问您的库存。 您可以从库存屏幕制作。",
    "You realize he has a point. You still don't know why your apprentice and your researcher are both eager to make weapons, but building a furnace could make it a lot easier to craft multiple types of items.": "你意识到他说的有道理。 你仍然不知道为什么你的学徒和你的研究员都渴望制造武器，但建造一个熔炉可以使制作多种类型的物品变得容易得多。",
    "You see your apprentice by the door of your room. You approach him and ask him what is wrong. He shakes a bit, but then finds courage and speaks.": "你在房间门口看到你的徒弟。 你走近他，问他怎么了。 他颤抖了一下，但随后鼓起勇气开口说话。",
    "A basic material for a lot of equipment, especially for spellcasters.": "许多设备的基本材料，尤其是施法者。",
    "A pair of uncomfortable, clunky sandals.": "一双不舒适、笨重的凉鞋。",
    "A small rock made out of condensed": "由法力凝结而成的小石头",
    "A sword: a mighty weapon in the hands of an expert.": "剑：高手手中的利器。",
    "A wooden club. Slightly heavy.": "一个木制的俱乐部。 有点重。",
    "An agile, lightweight weapon.": "敏捷、轻便的武器。",
    "An axe. Slow, but very damaging.": "斧头。 缓慢，但非常有害。",
    "As if reading your mind, a fat businessman with gaudy clothes shows up in campus. He grins at you, with a sneaky smile.": "仿佛读懂了你的心思，一个穿着华而不实的胖商人出现在校园里。 他对你咧嘴一笑，带着狡黠的微笑。",
    "Club": "俱乐部",
    "Crystallized Mana": "法力结晶",
    "Dagger": "匕首",
    "Discard all": "全部丢弃",
    "Equip": "装备",
    "Hand Axe": "手斧",
    "Hand over a Lightweight Chest": "交出一个轻盈的胸膛",
    "Heavy chest protection, to withstand tough blows.": "厚重的胸部保护，承受重击。",
    "Iron Mail": "铁甲",
    "Lightweight Chest for that purpose? If you dooooo... I'll make sure to come back ooooften and buy your items, multiple times!\"": "为此目的的轻型胸部？ 如果你真的……我会确保经常回来买你的东西，多次！”",
    "Raise Conjuration and Enchantment to Lv3 or above": "将咒语和附魔提升到Lv3或以上",
    "Selling Items": "出售物品",
    "Sword": "剑",
    "Temperature": "温度",
    "That's like music to your ears! But then the businessman continues.": "这就像您耳中的音乐！ 但随后商人继续。",
    "The new crafting table is doing well, but every time you get rid of an item to make room for another, you feel a little bad inside.": "新的工作台运行良好，但每次你摆脱一个项目为另一个项目腾出空间时，你的内心都会感觉有点糟糕。",
    "Total owned: 1": "拥有总数：1",
    "Wooden Sandals": "木凉鞋",
    "Wool": "羊毛",
    "You notice he already has a backpack...": "你注意到他已经有了一个背包...",
    "\"Gooooood afternoon, headmaster\", he exclaims to you. He looks at your item collection for a short while, then turns to you again. \"May I interest you in a business propooooosal?\"": "“下午好啊，校长”，他对你说。 他看了一会儿你的物品收藏，然后又转向你。 \“我可以对你的商业提议感兴趣吗？\”",
    "\"Of cooourse, that is only possible if I can carry them! You are a very talented individual. Would you be able to craft me a": "“当然，只有我能扛得住才行！你是一个非常有才华的人，你能不能给我做一个",
    "\"You have some very interesting items here\", he says. \"I would very much like to have them! I'd be happy to even offer you a bit of cooooins for them.\"": "“这里有一些非常有趣的物品”，他说。 \“我非常想拥有它们！我什至愿意为它们提供一些 cooooins。\”",
    "Sickle": "镰刀",
    "Quest Item": "任务物品",
    "Oh no!": "噢，不！",
    "New craftable items:": "新的可制作物品：",
    "Lightweight Chest": "轻型胸甲",
    "It looks like bandits have looted one of your vaults! You notice a significant amount of coins missing. Frustrated, you hope to catch them next time...": "看来强盗洗劫了您的一个金库！ 您注意到丢失了大量金币。 沮丧，你希望下次能抓住他们......",
    "Bandits!": "强盗！",
    "Appease the businessman": "安抚商人",
    "An oven with a very hot flame. Useful for crafting.": "有非常热的火焰的烤箱。 对制作很有用。",
    "Amount active:": "可用数量",
    "A weapon often used by farmers... or by reapers.": "农民经常使用的武器……或收割者。",
    "A very light wooden chest. Great for carrying items.": "一个非常轻的木箱。 非常适合携带物品。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Mana Spout": "法力喷泉",
    "Mana Shard": "法力碎片",
    "(Enchantment Lv": "（附魔 等级",
    "(Conjuration Lv": "（召唤 等级",
    "(Illusion Lv": "（幻觉 等级",
    "You obtained ": "你获得了 ",
    "You obtain ": "你获得了 ",
    "Water Tank": "水箱",
    "Warehouse": "仓库",
    "Lumber Yard": "伐木场",
    "Your Conjuration level is now ": "你的召唤等级现在是 ",
    "Researcher Cabin": "研究员小屋",
    "Apprentice Dorm": "学徒宿舍",
    "Mana Geyser": "法力间歇泉",
    "Mana Geysers": "法力间歇泉",
    "Your Illusion level is now ": "你现在的幻觉等级是 ",
    "Vault": "金库",
    "Conjuration Lv": "召唤等级",
    "Your Enchantment level is now ": "你的附魔等级现在是 ",
    "You lose ": "你失去了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "You pick up the staff. It's cursed! You feel your mana getting drained.": "你捡起了法杖。 它被诅咒了！ 你觉得你的法力正在耗尽。",
    "A staff was found on the ground.": "在地上发现了一把法杖。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。",
    "A traveling merchant appears at the campus gates and approaches you. \"Look at this\", he says, while getting a moist bag out from his pockets. He opens the bag, and shows you a small stone. You notice the stone seems to be emanating water.\n      \n\"This pebble magically produces water\", he says. \"This might be useful to you. It can be yours for 1500 coins. Would you like to purchase it?\"": "一位旅行商人出现在校园门口并接近你。 “看看这个”，他一边说，一边从口袋里掏出一个湿漉漉的袋子。 他打开袋子，给你看一块小石头。 你注意到石头似乎在散发水。\n \n\“这颗鹅卵石神奇地产生了水”，他说。 \“这个可能对你有用，1500金币就可以入手了，要不要买？”",
    "Gathering Mana is useful, but why would you do it if you had nothing to use it for?\n\nYou slowly recall how to cast spells and remember a basic Conjuration spell, *Create Pebble*. You think of trying it soon!\n\n**You have unlocked the ability to cast spells! You can cast spells by pressing the wand icon at the top right corner of the screen.**": "收集法力很有用，但如果你没有什么用，你为什么要这样做呢？\n\n你慢慢回忆起如何施法并记住一个基本的召唤法术，*创建鹅卵石*。 你想尽快尝试一下！\n\n**你已经解锁了施法的能力！ 您可以通过按屏幕右上角的魔杖图标来施法。**",
    "The mana reserves of the school are building up. Looking at them, you realize they may soon hit their maximum.\n    \nIf only you had a way to store more mana... Then you remember what you had learned as an apprentice, that Mana Shards can increase capacity.\n    \nWe could buy some if we had enough coins... maybe with some Illusion spell?\n\n**You can now build Mana Shards!**": "学校的法力储备正在增加。看着它们，你会意识到它们可能很快就会达到最大值。\n \n要是你有办法储存更多的法力就好了......然后你会想起你作为学徒学到的东西，法力碎片可以增加容量。\n \n如果我们有足够的金币，我们可以买一些......也许用一些幻觉法术？\n\n**你现在可以建造法力碎片了！**",
    "It looks like our mana spouts are suddenly bursting with activity and producing Mana twice as fast!": "看起来我们的法力喷泉突然充满活力并以两倍的速度产生法力！",
    " Max": " 上限",
    "Accumulating stone is worthwhile. As you watch your reserves getting closer to full, you start thinking if there might be a way to improve the situation.\n    \nMaybe you can use the stone to create more room? It seems like a smart, straightforward idea... you could make a stone warehouse.\n\n**You can now build Warehouses!**": "积累石头是值得的。 当你看到你的储备越来越接近饱和时，你开始思考是否有办法改善这种情况。\n \n也许你可以用石头创造更多空间？ 这似乎是一个聪明、直接的想法……你可以建造一个石头仓库。\n\n**你现在可以建造仓库了！**",
    "Our studies of magic are starting to become more fruitful! With our recent advances, we are ready to start broadening our horizons. The campus is big, but there is only so much in it!\n    \nIt seems like there is a nearby forest where we may be able to find wood, which could help us develop our institution even further...\n\n**You can now gather:wood: Wood!**": "我们对魔法的研究开始变得更有成果了！ 随着我们最近的进展，我们准备开始拓宽我们的视野。 校园很大，但里面只有这么多！\n\n好像附近有一片森林，我们可以在那里找到木材，这可以帮助我们进一步发展我们的机构......\n\n **你现在可以收集：木头：木头！**",
    "These trips to the forest are starting to get tedious. You are starting to wonder if there is a way you could make it easier on yourself.\n    \nPerhaps there is a way? Maybe we can reuse the wood we obtained to make something bigger? You get lost in thought as you walk back to campus.\n\nBy the time you arrive, you have figured it out. Lumber yards right at the edge of the forest. It can surely work!\n\n**You can now build Lumber Yards!**": "这些森林之旅开始变得单调乏味。 您开始想知道是否有一种方法可以让您自己更轻松。\n \n也许有一种方法？ 也许我们可以重新利用我们获得的木材来制造更大的东西？ 当您走回校园时，您陷入了沉思。\n\n当您到达时，您已经想通了。 伐木场就在森林的边缘。 它肯定可以工作！\n\n**你现在可以建造伐木场了！**",
    "You have been struggling with water storage for a while. Creating it is easy, but you have nowhere to place it - it just drops to the ground!\n    \nYou feel a surge of inspiration, as you realize you could build a container. Then you figure it's downright obvious.\n\nYou set out to build a water tank with stone and wood.\n\n**You can now build Water Tanks!**": "您已经为储水问题苦苦挣扎了一段时间。 创建它很容易，但您无处放置它 - 它只会掉到地上！\n \n当您意识到可以建造一个容器时，您会感到灵感涌动。 然后你觉得这很明显。\n\n你开始用石头和木头建造一个水箱。\n\n**你现在可以建造水箱了！**",
    "You look at her, perplexed and somewhat confused. Then she continues explaining.\n\n\"Large amounts of Mana are hard to come by, and are almost a requirement for the successful study of Magic.\"": "你看着她，困惑又有些困惑。 然后她继续解释。\n\n\“大量的魔力很难获得，而且几乎是成功学习魔法的必要条件。”",
    "\"Are you trying to study magic here? This is exciting!\n            \nI'd be willing to work here for a small price... let's say 200 Coins. Of course, you would be the first to learn what I find out, and you would be able to tell me what I should focus on,\" she says earnestly.\n\n\"So what will it be?\"": "\"你是想在这里学习魔法吗？这太令人兴奋了！\n \n我愿意在这里工作，只要一个小价钱……比方说 200 币。当然，你会是第一个学到我发现的东西的人出来，你就能告诉我应该关注什么，”她认真地说。\n\n\“那会是什么呢？\”",
    "You produce 200 coins out of your pockets, and hand them over to the researcher. She looks at the coins and puts them away in the pockets of her robes.\n\n\"Perfect! I will get started right away. I'm sure this is the beginning of a very fruitful relationship for us both!,\" she exclaims.\n\n**You have unlocked the \"Research\" feature! You may find it on the left-side menu.**": "你从口袋里掏出 200 个金币，交给研究人员。 她看着硬币，把它们放在长袍的口袋里。\n\n\“太棒了！我会马上开始。我相信这对我们双方来说是一段非常富有成果的关系的开始！，\ ”她惊呼道。\n\n**你已经解锁了“研究”功能！ 您可以在左侧菜单中找到它。**",
    "Your researcher comes up to you. \"Studying here has been great so far!\", she says. \"But it certainly is somewhat lonely... it would be great to have company. We could get double the work done; imagine how fast we could discover new things!\", she exclaims.\n    \n\"But there's a problem. There's nowhere for them to stay in. I have an idea for a cabin, but... we'll need to build it, first. Oh well.. back to work,\" she mentions, as she turns away and continues focusing on her research.\n\nYou ponder her words for some time. Regardless of her feelings, you recognize that double the researchers could greatly speed things up. You think of possibly building a Researcher Cabin as she suggested, and hiring an extra researcher.\n\n**You can now build Researcher Cabins!**": "你的研究员来找你。 “到目前为止，在这里学习一直很棒！”，她说。 \“但它确实有点孤独……有人陪伴会很棒。我们可以完成双倍的工作；想象一下我们发现新事物的速度有多快！\”，她惊呼道。\n \n\“但是有“一个问题。他们没有地方可以住。我有个小木屋的主意，但是……我们首先需要建造它。哦，好吧……回去工作吧，”她转身离开时说道并继续专注于她的研究。\n\n你思考了她的话一段时间。 不管她的感受如何，你认识到双倍的研究人员可以大大加快速度。你考虑可能按照她的建议建造一个研究员小屋，并雇用一名额外的研究员。\n\n**你现在可以建造研究员小屋了！**",
    " Max Researchers": " 研究员上限",
    "Your researchers seem to have a burst of inspiration! They will be studying twice as hard for a short time.": "你的研究人员似乎灵感迸发！ 他们将在短时间内加倍努力学习。",
    "How many times have you manually cast a spell by now? You have lost count. It certainly is not difficult for you. However, there is real repetition to these casts.\n    \nYou wonder if there might be a way to somehow automate this, as it's starting to feel a bit dull. But thinking about it, you can't figure out any solution...": "你现在手动施法多少次了？ 你数不清了。 这对你来说当然不难。 然而，这些转换确实有重复。\n \n你想知道是否有办法以某种方式自动执行此操作，因为它开始感觉有点乏味。 但是想想也想不出什么办法……",
    "Your researcher walks up to you. She is together with a shaky individual, who seems to be barely breaking into adulthood and appears scared at your sight.\n\n\"I have a great idea!\", she says. \"This is my cousin. He is a wizard-in-training... an apprentice wizard,\" she continues, while gazing at him, before looking at you once more.": "你的研究员走到你身边。 她和一个摇摇欲坠的人在一起，这个人似乎几乎没有进入成年期，一看到你就害怕。\n\n\“我有一个好主意！\”，她说。 “这是我的堂兄。他是一名受训巫师……一名学徒巫师，”她继续说道，同时注视着他，然后又再次看着你。",
    "\"It is a honor to meet you, headmaster,\" exclaims the apprentice, while bowing at you somewhat too deeply.\n\nThe researcher continues. \"It'd be great to have him stay here! He could help you cast spells and continue improving our campus. Besides, a magical institution makes no sense without people who'd like to learn. What do you think?\", she asks you.\n\nYou recall thinking about how tedious it was to cast spells. This could be a big help!": "“很荣幸见到您，校长，”学徒大声说道，同时向您深深地鞠了一躬。\n\n研究员继续说道。 \"让他留在这里就好了！他可以帮助你施法，继续改善我们的校园。而且，没有愿意学习的人，一个魔法机构就没有意义。你怎么看？\",她问你。\n\n你记得想过施法是多么乏味。 这可能是一个很大的帮助！",
    "As you slowly start getting more and more iron, you think of a plan to improve on your Mana Spouts. You are thinking that, by adding iron, you should be able to create a structure that can produce mana at a much faster rate than a simple spout.\n    \nYou will definitely require a lot of iron, but it'll be worth it in the long run, you tell yourself. Mana is the cornerstone of magic!\n\n**You can now build Mana Geysers!**": "随着您慢慢开始获得越来越多的铁，您想到了一个改进 Mana Spouts 的计划。 你在想，通过添加铁，你应该能够创建一个可以比简单的喷口更快地产生法力的结构。\n \n你肯定需要很多铁，但这是值得的从长远来看，你告诉自己。 法力是魔法的基石！\n\n**你现在可以建造法力间歇泉了！**",
    "Your researcher calls your attention. \"There is a place you should see\", she exclaims, walking outside the campus. \"Follow me.\" You do as instructed.\n    \nYou end up in what seems to be a fairly rocky cliff. However, you notice the rock in a wall shining a different color. \"That's iron,\" your researcher says. \"This is a sturdy metal. Not too useful for casting magic, but it could be great for buildings... or...\"\n\nYou agree with her. Learning about this place for the first time, you thank the researcher. You'll be sure to come back prepared next time - this could be useful!\n\n**You unlocked the ability to gather iron!**": "您的研究人员引起您的注意。 “有一个地方你应该去看看”，她在走出校园时大声说道。 \"跟我来。\"你按照指示去做。\n \n你最终来到了一个看起来相当多岩石的悬崖。 但是，您注意到墙上的石头闪耀着不同的颜色。 “那是铁，”你的研究人员说。 \“这是一种坚固的金属。对施法不太有用，但对建筑来说可能很棒……或者……\”\n\n你同意她的看法。 第一次知道这个地方，谢谢研究员。 下次你一定会做好准备 - 这可能会有用！\n\n**你解锁了收集铁的能力！**",
    "\"There's just a little problem,\" the researcher continues. \"There is nowhere for him to sleep in! We'll need to build something.\"\n            \nYou saw it coming. Still, you can't wait - you've had enough casting *Create Pebble* manually. You reassure the researcher and her cousin that you will think about it, and you walk away, starting to picture what you would need to construct suitable housing for your first apprentice.\n\n**You can now build Apprentice Dorms!**": "“只是有点问题，”研究人员继续说道。 \"他没有地方睡觉！我们需要建造一些东西。\"\n \n你看到它来了。 不过，您已经迫不及待了 - 您已经进行了足够多的手动铸造 *创造鹅卵石*。 你向研究员和她的表妹保证你会考虑这个问题，然后你走开，开始想象你需要什么来为你的第一个学徒建造合适的住房。\n\n**你现在可以建造学徒宿舍了！**",
    "You are managing to stockpile large amounts of coins! It would be wise to find a place to put them in.\n    \nWarehouses have been useful; stone has proven to be a good material for tons of things. You think about using it for a specialized building for money storage. You are concerned about bandits, but are convinced it'll be worth it in the long run.\n\n**You can now build Vaults!**": "您正在设法储存大量硬币！ 找个地方把它们放进去是明智的。\n \n仓库一直很有用； 事实证明，石头是制作大量物品的好材料。 您考虑将其用于专门用于存放货币的建筑物。 你担心强盗，但相信从长远来看这是值得的。\n\n**你现在可以建造保险库了！**",
    "Construction for the first apprentice dorm is finished! You celebrate to a small audience. You notice the apprentice from before is still there. You approach him, though he still seems fearful and bows deeply.\n    \n\"Is that... housing I could use?\", he says, with a timid voice. You nod, and ask him if he'd like to become your first apprentice. He shakes, visibly and clearly nervous.\n\n\"That would be great... I-It's a honor, to be able to learn from one such as you, headmaster. I'll move in right away.\"\n\n**You have unlocked Apprentices! Apprentices can automatically cast spells for you after a set amount of time. You may manage them in the Apprentices section, in the left-hand-side menu.**": "第一个学徒宿舍建设完成！ 你向一小群观众庆祝。 你注意到之前的学徒还在。 你走近他，尽管他看起来仍然很害怕并深深地鞠躬。\n \n\“那是……我可以使用的住所吗？\”，他用胆怯的声音说道。 你点点头，问他愿不愿意做你的第一个学徒。 他颤抖着，显然很紧张。\n\n\“那太好了……我-很荣幸能够向校长这样的人学习。我马上搬进去。” \n\n**你已经解锁了学徒！ 学徒可以在一定时间后自动为您施法。 您可以在左侧菜单的学徒部分管理它们。**",
    "Your researcher approaches you and mentions something to you.\n  \n\"Headmaster, I think you may already be aware, but - now that we have a proper, true magical institution, we should start thinking about the *Tournament of Magic*.\" You are not sure of what she means by that, but she continues: \"The Tournament of Magic is a competition between magical institutions. It is a major event in regards to the research of magic, and those who manage to compete in it - let alone the winner - are sure to get great fame and prosperity.\"\n\n\"It could really take our school to new heights!\", she exclaims.\n\nYou talk to her some more, and you start feeling like it is a great goal to have... though you know you are nowhere close to reaching it. At least for now...": "你的研究员走近你并向你提到了一些事情。\n \n\“校长，我想你可能已经意识到了，但是 - 现在我们有了一个合适的，真正的魔法机构，我们应该开始考虑*魔法锦标赛* .” 你不清楚她的意思，但她继续说道：“魔法锦标赛是魔法机构之间的比赛，是魔法研究领域的盛会，能够参赛的人在其中 - 更不用说获胜者 - 肯定会获得巨大的名望和繁荣。\"\n\n\"它真的可以把我们的学校带到新的高度！\"，她惊呼道。\n\n你再和她谈谈，你开始觉得这是一个伟大的目标......虽然你知道你离实现它还差得很远。 至少现在...",
    "You continue listening to her.\n          \n\"If we had a crafting station, we could make a lot of these... if only it wasn't so expensive to build, I could do it myself and learn more about it!\", she says, somewhat frustrated.\n\nYou aren't sure whether to pay heed to it - why would you need things like weapons in a magical institution? You think about it some more...": "你继续听她说。\n \n\“如果我们有一个制作站，我们可以制作很多这样的......只要建造起来不那么昂贵，我可以自己做并学到更多关于它！\"，她有些沮丧地说。\n\n你不确定是否要注意它 - 为什么你需要在魔法机构中使用武器之类的东西？ 你再考虑一下...",
    "You try to convey to your researcher that we have, in fact, been creating complex things from resources: the buildings. But she frowns.\n      \n\"No, that's not what I meant\", she says, unhappily. \"Buildings are huge! I'm thinking more of useful, smaller things. Potions? Weapons? Magical items?\"": "您试图向您的研究人员表明，我们实际上一直在从资源（建筑物）中创造复杂的事物。 但她皱起眉头。\n \n\“不，我不是那个意思\”，她不高兴地说。 \“建筑物很大！我在想更有用的、更小的东西。药水？武器？魔法物品？”",
    "Your focus is interrupted by your researcher, who yells at you. \"Headmaster!\", she says.\n\n\"Gathering resources like wood and iron is great\", she continues. \"Wouldn't it even be more interesting if we could make more complex stuff from them?\"": "你的注意力被你的研究员打断了，他对你大喊大叫。 \“校长！\”，她说。\n\n\“收集木材和铁等资源很棒\”，她继续说道。 \“如果我们能用它们制造更复杂的东西，会不会更有趣？”",
    "One of your researchers seems to have come across a dusty book. The book seems to contain knowledge about Conjuration. Thrilled, your researchers get back to work with the new knowledge.\n  \n  **You gain 3045 Conjuration experience!**": "",
    "You use your Illusion prowess to charm the merchant into thinking positively about you. Without noticing, he says: \"Actually... 1500 coins is quite a high price. I'd be happy to give you a *very* good deal. I can't go lower than 150 coins, though. Are you interested?": "你用你的幻觉能力来吸引商人对你产生积极的看法。 不知不觉，他说：“其实……1500个金币是个高价。我很乐意给你一个*非常*划算的交易。不过我不能低于150个金币。你有兴趣吗？” ？",
    "\"Great doing business with you!\", he exclaims, taking your coins. Placing the pebble back inside the bag, he hands over the bag to you.\n      \n  This magical stone will come in handy!": "“和你做生意真好！”他接过你的硬币时大声说道。 把鹅卵石放回袋子里，他把袋子递给你。\n \n 这块神奇的石头会派上用场的！",
    "It was difficult, but the crafting station is finished! Your researcher, filled with joy, runs towards it and examines it from every angle. You notice your apprentice also taking notice of it, and looking at it curiously.\n              \nA crafting station... You wonder if you might be able to do something with it right away?\n\n\"Conjuration and Enchantment,\" says your researcher, as she passes by you with the apprentice. \"Focus our research in those schools, and we should be able to make items.\" They head outside together.\n\n**You have unlocked the \"Inventory\" and \"Crafting\" features! You can access your inventory via the left-side menu. You can craft from the inventory screen.**": "这很困难，但制作站已经完成了！ 您的研究人员满怀喜悦地奔向它，并从各个角度审视它。 你注意到你的学徒也注意到了它，并好奇地看着它。\n \n一个手工制作站......你想知道你是否可以马上用它做点什么？\n\n\“咒法和附魔， \"当她和学徒从你身边经过时，你的研究员说。 \“将我们的研究集中在那些学校，我们应该能够制造物品。\”他们一起走到外面。\n\n**你已经解锁了“库存”和“制作”功能！ 您可以通过左侧菜单访问您的库存。 您可以从库存屏幕进行制作。**",
    "You see your apprentice by the door of your room. You approach him and ask him what is wrong. He shakes a bit, but then finds courage and speaks.\n\n\"I-I have been thinking about crafting, but it's very hard to shape metal right now,\" he says. \"Maybe if we had a really hot flame, we would be able to be much more effective with crafting... maybe even make real weapons?\"\n\nYou realize he has a point. You still don't know why your apprentice and your researcher are both eager to make weapons, but building a furnace could make it a lot easier to craft multiple types of items.\n\n**You can now build Furnaces!**": "你在房间门口看到你的徒弟。 你走近他，问他怎么了。 他颤抖了一下，但随后鼓起勇气说话。\n\n\“我-我一直在考虑手工制作，但现在很难塑造金属，”他说。 \“也许如果我们有真正炽热的火焰，我们就能更有效地制作……甚至可以制作真正的武器？\”\n\n你意识到他说的有道理。 你仍然不知道为什么你的学徒和你的研究员都渴望制造武器，但是建造一个熔炉可以使制作多种类型的物品变得容易得多。\n\n**你现在可以建造熔炉了！**",
    "\"You have some very interesting items here\", he says. \"I would very much like to have them! I'd be happy to even offer you a bit of cooooins for them.\"\n        \nThat's like music to your ears! But then the businessman continues.\n\n\"Of cooourse, that is only possible if I can carry them! You are a very talented individual. Would you be able to craft me a :lightweightChest: Lightweight Chest for that purpose? If you dooooo... I'll make sure to come back ooooften and buy your items, multiple times!\"\n\nYou notice he already has a backpack...": "“这里有一些非常有趣的物品”，他说。 \"我非常想拥有它们！我什至愿意为它们提供一些 coooins。\"\n \n这对你的耳朵来说就像音乐！ 但随后商人继续说道。\n\n\“当然，只有我可以携带它们才有可能！你是一个非常有才华的人。你能为我制作一个 :lightweightChest：为此目的的轻量级箱子吗？如果你真的......我会确保经常回来买你的东西，多次！\"\n\n你注意到他已经有了背包......",
    "The new crafting table is doing well, but every time you get rid of an item to make room for another, you feel a little bad inside.\n    \nAs if reading your mind, a fat businessman with gaudy clothes shows up in campus. He grins at you, with a sneaky smile.\n\n\"Gooooood afternoon, headmaster\", he exclaims to you. He looks at your item collection for a short while, then turns to you again. \"May I interest you in a business propooooosal?\"": "新的工作台做得很好，但每次你摆脱一件物品为另一件物品腾出空间时，你的内心都会感觉有点糟糕。\n \n就像读懂了你的想法一样，一个穿着华而不实的胖商人出现在校园里。 他对你咧嘴一笑，偷偷摸摸地笑着。\n\n\“下午好，校长”，他对你喊道。 他看了一会儿你的物品收藏，然后又转向你。 \“我可以对你的商业提议感兴趣吗？\”",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^(.+)Welcome back to Magic Research!\n      \n\*\*You obtained (.+):timepiece: Time Pieces! Time Pieces allow you to make time pass faster for a duration. You can do so from the left side menu!\*\*$/, '$1欢迎回到魔法研究！\n \n**您获得了 $2:时光碎片：时间碎片！ 时间碎片可以让你在一段时间内让时间过得更快。 您可以从左侧菜单执行此操作！**'],
    [/^(.+)Welcome back to Magic Research!\n      \n\*\*You obtained (.+):timepiece: Time Pieces!\*\*$/, '$1欢迎回到魔法研究！\n \n**您获得了 $2:时光碎片：时间碎片！ **'],
    [/^(.+)Congratulations!\n      \nYour Illusion level is now (.+)!\n\n\n$/, '$1恭喜！\n \你的幻觉等级现在是 $2！\n\n\n'],
    [/^(.+)Congratulations!\n      \nYour Illusion level is now (.+)!\n\n\*\*New spells learned:\*\* \*Flame Show\* \(Illusion Lv(.+)\)\n$/, '$1恭喜！\n \你的幻觉等级现在是 $2！\n\n**学到的新法术：** *火焰表演*（幻觉 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Illusion level is now (.+)!\n\n\*\*New spells learned:\*\* \*Wind Show\* \(Illusion Lv(.+)\)\n$/, '$1恭喜！\n \你的幻觉等级现在是 $2！\n\n**学到的新法术：** *驭风表演*（幻觉 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Illusion level is now (.+)!\n\n\*\*New spells learned:\*\* \*Bubble Show\* \(Illusion Lv(.+)\)\n$/, '$1恭喜！\n \你的幻觉等级现在是 $2！\n\n**学到的新法术：** *泡沫表演*（幻觉 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\*\*New spells learned:\*\* \*Create Rock\* \(Conjuration Lv(.+)\)\n$/, '$1恭喜！\n \你的召唤等级现在是 $2！\n\n**学到的新法术：** *创造石头*（召唤 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\*\*New spells learned:\*\* \*Create Boulder\* \(Conjuration Lv(.+)\)\n$/, '$1恭喜！\n \你的召唤等级现在是 $2！\n\n**学到的新法术：** *创造巨石*（召唤 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Enchantment level is now (.+)!\n\n\*\*New spells learned:\*\* \*Enchant Lumber Yards\* \(Enchantment Lv(.+)\)\n$/, '$1恭喜！\on \你的附魔等级现在是 $2！\n\n**学到的新法术：** *附魔伐木场*（附魔 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Enchantment level is now (.+)!\n\n\n\n\*\*New craftable items:\*\*\n:lightweightChest:\*Lightweight Chest\* \(Conjuration Lv(.+), Enchantment Lv(.+)\)$/, '$1恭喜！\n \n你的附魔等级现在是 $2 级！\n\n\n\n**新的可制作物品：**\n：lightweightChest：*Lightweight Chest*（召唤 等级$3，附魔 等级$4）'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\*\*New spells learned:\*\* \*Create Iron Bar\* \(Conjuration Lv(.+)\)\n$/, '$1恭喜！\on \你的召唤等级现在是 $2！\n\n**学到的新法术：** *创造铁锭*（召唤 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\*\*New spells learned:\*\* \*Create Water (.+)\* \(Conjuration Lv(.+)\)\n$/, '$1恭喜！\on \你的召唤等级现在是 $2！\n\n**学到的新法术：** *创造水 $3*（召唤 等级$4）\n'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\*\*New spells learned:\*\* \*Create Iron Ore\* \(Conjuration Lv(.+)\)\n$/, '$1恭喜！\on \你的召唤等级现在是 $2！\n\n**学到的新法术：** *创造铁矿石*（召唤 等级$3）\n'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\n\n\*\*New craftable items:\*\*\n:sickle:\*Sickle\* \(Conjuration Lv(.+)\)$/, '$1恭喜！\on \你的召唤等级现在是 $2！\n\n\n\n**新的可制作物品：**\n:镰刀:*镰刀*（召唤 等级$3）'],
    [/^(.+)Congratulations!\n      \nYour Conjuration level is now (.+)!\n\n\n$/, '$1恭喜！\on \你的召唤等级现在是 $2！\n\n\n'],
    [/^(.+)You find a pile of stone as you walk through campus. You are not sure why it's there, but it seems misplaced. You decide to take it.\n        \n\*\*You obtain (.+):stone:!\*\*$/, '$1当你穿过校园时，你会发现一堆石头。 你不确定它为什么在那里，但它似乎放错了地方。 你决定接受它。\n \n**你获得 $2:石头:!**'],
    [/^(.+)You stumble upon a pile of wood as you walk through campus. You are not sure why it's there, but it seems misplaced. You decide to take it.\n        \n\*\*You obtain (.+):wood:!\*\*$/, '$1当你穿过校园时，你偶然发现了一堆木头。 你不确定它为什么在那里，但它似乎放错了地方。 你决定接受它。\n \n**你获得 $2:木头:!**'],
    [/^(.+)One of your researchers seems to have come across a dusty book. The book seems to contain knowledge about Conjuration. Thrilled, your researchers get back to work with the new knowledge.\n  \n  \*\*You gain (.+) Conjuration experience!\*\*$/, '$1您的一位研究人员似乎遇到了一本布满灰尘的书。 这本书似乎包含有关召唤的知识。 兴奋不已，你的研究人员开始使用新知识开展工作。\n \n **你获得 $2 点召唤经验！**'],
    [/^(.+)\*Oh no!\* It looks like bandits have looted one of your vaults! You notice a significant amount of coins missing. Frustrated, you hope to catch them next time...\n        \n\*\*You lose (.+):coins:!\*\*$/, '$1*哦不！* 看来土匪洗劫了您的一个金库！ 您注意到丢失了大量硬币。 沮丧，你希望下次能抓住他们...\n \n**你失去了 $2:金币:!**'],
    [/^You gain (.+) Conjuration experience!$/, '你获得了 $1 点召唤经验！'],
    [/^If you retire now, your research multiplier will become (.+)x \(\+(.+)\%\) and your production and loot multiplier will become (.+)x \(\+(.+)\%\).$/, '如果您现在退休，您的研究乘数将变为 $1x（+$2%），您的生产和战利品乘数将变为 $3x（+$4%）。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Conjuration Lv(.+) \(Primary\)$/, '召唤 等级$1（初级）'],
    [/^Enchant Mana Spouts \((.+) sec\)$/, '附魔法力喷泉（$1 秒）'],
    [/^Enchant Lumber Yards \((.+) sec\)$/, '附魔伐木场（$1 秒）'],
    [/^Illusion Lv(.+)$/, '幻觉 等级$1'],
    [/^Enchantment Lv(.+)$/, '附魔 等级$1'],
    [/^s bursting with activity! \((.+) sec\)$/, '充满活力！（$1 秒）'],
    [/^Your researchers are inspired! \((.+) sec\)$/, '您的研究人员受到启发！（$1 秒）'],
    [/^Charm the merchant \((.+) Mana\)$/, '魅惑商人（$1 法力值）'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) days, ([\d\.]+):([\d\.]+):([\d\.]+)$/, '$1 天，$2:$3:$4'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Slot ([\d\.,]+)$/, '插槽 $1'],
    [/^\+([\d\.,]+) Max Apprentices$/, '+$1 学徒上限'],
    [/^\+([\d\.,]+) Researcher$/, '+$1 研究员'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);